spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crud_server?serverTimezone=UTC
    username: root
    password: root
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

server:
  port: 9090